### ISSUE TITLE
File encoding forcing seems to run for binary files as well.

### ISSUE THREAD

**Issue by chrisdanek** [mdyd-dev/marketplace-kit#11]
When I run marketplace-kit sync I constantly get a following message
```
Updating: /Users/Chris/Sites/hallmark/marketplace_builder/custom_themes/default_custom_theme_assets/logo-white.png
Error: source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
```

It’s consistent for all .png images. I think it also messes with .woff files. I think checking if encoding forcing should be applied is failing.

**Comment by piotrze** [comment]
@chrisdanek Fix is in master will be in next release

**Comment by chrisdanek** [comment]
Looks like it’s working just fine now 👍
