### ISSUE TITLE
Form validation error message missing on sync and deploy

### ISSUE THREAD

**Issue by MattJonesSiteglide** [mdyd-dev/marketplace-kit#113]
## Expected behavior 
Either syncs file successfully or displays error message if there is a problem with syncing a form. 

Deploying should also show an error message if something in a file was preventing the deploy.

## Actual behavior
Although it would not sync correctly, the message in terminal was green and said done. However, the form did not update on the server. Removing validation allowed the file to sync correctly.

At the same time, deploy did not tell me it had failed- but continued to run without end. 

## Steps to reproduce the problem

Create a form with the following validation on a field:
`content_producer_mandatory:
   validation: 
     presence:
       true:`

Try and make changes to the HTML content to the form and sync and deploy.

### NodeJs
npm: version 6.5.0
node version v8.12.0
### Operating System

Windows 10

Instance: https://uat-uipath-go.oregon.near-me.com/dashboard/become-a-contributor

**Comment by ignacy** [comment]
Tried this on the latest Platform & Marketplace Kit and I could not reproduce the error. On deploy it does not hang but finishes correctly, sync works as usual as far as I can tell.
