### ISSUE TITLE
It should be possible to start GUI even if port is taken

### ISSUE THREAD

**Issue by lemingos** [mdyd-dev/marketplace-kit#115]
## Expected behavior 

it should be possible to run gui for multiple instances

## Actual behavior

Error is raised:

```
marketplace-kit gui serve dash-6
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3333
```
## Steps to reproduce the problem
start gui for more than once instance

### Marketplace Kit
2.7
### NodeJs
all
### Operating System
all

**Comment by ignacy** [comment]
There is  `-p --port <port>', 'use PORT', '3333'` option so what should really happen here is a better error message
