### ISSUE TITLE
[401] HTTP Token Access Denied - with correct credentials

### ISSUE THREAD

**Issue by niko-cbo** [mdyd-dev/marketplace-kit#117]
## Expected behavior 
I am able to run `marketplace-kit-gui serve env` with my credential

## Actual behavior
I am not able to access it - https://cbo.d.pr/Zi0SRc

## Steps to reproduce the problem
The email I am using has a "+" character "niko+cbo@cbo.me"

### Marketplace Kit
v2.7.0

### NodeJs
v10.8.0

### Operating System
Mac OS High Sierra v10.13.6

**Comment by pavelloz** [comment]
Try using `marketplace-kit gui serve env`
Note: space, not dash

**Comment by niko-cbo** [comment]
hi @pavelloz ,

Thank you for your suggestion.
I tried it again with `marketplace-kit-gui` and now it works, not sure why.

Issue can now be closed.
