### ISSUE TITLE
[Bug] Missing file content on incorrect template parse

### ISSUE THREAD

**Issue by lemingos** [mdyd-dev/marketplace-kit#143]
## Expected behavior 
Should raise validation error when rendering template fails.

## Actual behavior

Missing file content when error occures.

in lib/templates.js
```
const fillInTemplateValues = path => {
  const fileBody = fs.readFileSync(path, 'utf8');
  try {
    return mustache.render(fileBody, templateData(), {}, tags);
  } catch (err) {
    logger.Debug(err);
    return '';
  }
};
```

we retuern empty string in case or error

## Steps to reproduce the problem

Add variable without closting tag `<%=`

## Version:
all
### Marketplace Kit
all
### NodeJs
all
### Operating System
all

**Comment by Slashek** [comment]
fixed
