### ISSUE TITLE
Templates file

### ISSUE THREAD

**Issue by pavelloz** [mdyd-dev/marketplace-kit#145]
https://github.com/mdyd-dev/marketplace-kit/pull/121

This looks like all data is in root of the object, without any scoping for module that is supposed to use the variable. This is going to end very badly.

I propose for modules:

* feedback
* contacts

make it so that both can use the same variable name.

```
{
  "feedback": {},
  "contacts": {}
}
```

**Comment by lemingos** [comment]
https://github.com/mdyd-dev/marketplace-kit/issues/144 I think you've reported the same issue

**Comment by pavelloz** [comment]
Nope. Im just saying about json structure.

I was thinking something similar to 144 at first, but this seems like a much better first step to at least make this feature usable. Next iteration might be files separation, so far, i call YAGNI on that.
