### ISSUE TITLE
run `marketplace-kit audit` during deploy

### ISSUE THREAD

**Issue by Slashek** [mdyd-dev/marketplace-kit#192]
`marketplace-kit audit` is an amazing tool (which we neglect a little bit) to make sure everyone is up to date with deprecation and best practices. However, no one uses it, and many people probably don't know it. It seems like a good idea to automatically run audit during deploy and notify user about any warnings.

**Comment by pavelloz** [comment]
- [ ] fix tag regexp to actually find something

```
{%- meta_description -%}
{%-    meta_description -%}
{% meta_description -%}
{%    meta_description -%}

```

**Comment by pavelloz** [comment]
At the end, research leveraging eslint to handle the heavy load. Writing plugin might be faster and more appropriate.

**Comment by pavelloz** [comment]
Performance so far fixed by fast-glob

If not enough, try to replace shelljs with nak - its very possible it will be faster - https://yarnpkg.com/en/package/nak .
