### ISSUE TITLE
Show a warning whenever a graphql query with deprecated endpoint is synced

### ISSUE THREAD

**Issue by chrisdanek** [mdyd-dev/marketplace-kit#21]
Since our schema is still evolving we should notify users as soon as possible about deprecations. One way to do it would be to show a console warning whenever we sync or deploy. It should not prevent deploy, just output to console.

**Comment by piotrze** [comment]
Made some initial work https://github.com/piotrze/graphql-ruby/commit/0f20ace078a675ba6f0d521b23bc00018d980e3c

**Comment by pavelloz** [comment]
^ feel free to add your own rules here
https://github.com/mdyd-dev/marketplace-kit/blob/master/lib/audit/rules.js
