### ISSUE TITLE
Add confirmation option for deploy command

### ISSUE THREAD

**Issue by chrisdanek** [mdyd-dev/marketplace-kit#22]
Add an option in `.builder` to enable confirmation prompt per environment.

```
  "production": {
    "url": "https://example.com/",
    "confirm": true
  }
```

When running deploy / sync command it would first ask for: 

```You are about to change #NAME_OF_ENVIRONMENT# environment. Type in name of environment to proceed: ```

**Comment by ignacy** [comment]
Alternatively (or additionally), could we have a small delay (maybe 1-2 seconds) before the deploy actually happens? This would give us some time to Ctrl-C if we just got to the shell, pressed "arrow up" and hit enter thinking we're doing a local sync and forgetting we did a production deploy the day before 😉 

I'm asking for a friend if someone wonders 😉

**Comment by pavelloz** [comment]
There is a second of delay (zipping & sending zip) - if you cancel during those operations it should stop deploy

**Comment by pavelloz** [comment]
wrong button ;)
