### ISSUE TITLE
files are not backing up when running the "marketplace-kit pull -e production" command 

### ISSUE THREAD

**Issue by bkanawati** [mdyd-dev/marketplace-kit#23]
When I run the "marketplace-kit pull -e production" command. 
First I get a response that states to insert an email and then password. 
After that it responds with a message saying "pull command succeded"

no files were backed up in my file.

**Comment by pavelloz** [comment]
Hello @bkanawati 

Can you provide some additional information would help to reproduce the bug on a local machine.
* directory structure (`tree .`),
* marketplace kit gem version (`marketplace-kit -v`)

If you could also email me ( pawel@near-me.com ) endpoint URL that you are pulling that will allow me to check if thats something with marketplace-kit or maybe with the other side.

Thanks :)

**Comment by pavelloz** [comment]
Update:

It looks like windows env. doesn't have some of the commands used in the gem.

Those need to be replaced by their dependent equivalents.

See:
https://github.com/mdyd-dev/marketplace-kit/blob/master/lib/marketplace_kit/commands/pull.rb#L36-L37

**Comment by piotrze** [comment]
@bkanawati I've just tried to get it work on windows and if you are using windows10 it is fairly easy. All you need is to install ...... ubuntu :tada: 
https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6?ranMID=24542&ranEAID=nOD/rLJHOac&ranSiteID=nOD_rLJHOac-A46UjBUiJnAKeGxxADVrMw&tduid=(cfb8dd2f97b9305b0b81f92093a2842c)(256380)(2459594)(nOD_rLJHOac-A46UjBUiJnAKeGxxADVrMw)()

Then install ruby, marketplace-kit gem and you will find your disk at `/mnt/c`

```
ubuntu
sudo apt-get install gcc ruby ruby-dev libxml2 libxml2-dev  libxslt1-dev
sudo apt-get install marketplace-kit
cd /media/c/<somedirectorywithproject>
marketplace-kit pull -e staging
```

**Comment by Slashek** [comment]
alternatively, for now you can also go to `https://<your domain>/instance_admin/manage/marketplace_releases`, request marketplace backup and download the zip file manually

**Comment by pavelloz** [comment]
Both solutions seems pretty solid. Long term i would personally go with the first ubuntu route :)
