### ISSUE TITLE
Provide a list of available environments when an invalid one is given

### ISSUE THREAD

**Issue by chrisdanek** [mdyd-dev/marketplace-kit#27]
Right now when you enter an incorrect name of environment like so

    marketplace-kit sync -e invalid

You receive a following error

    Error: Invalid env passed!

It would be helpful to get a list of available environments from the `.builder` file

**Comment by godot** [comment]
@chrisdanek take a look at node-version of marketplace-kit env list - does it work for you?

**Comment by godot** [comment]
```
> marketplace-kit deploy missing
No settings for missing environment, please see marketplace-kit env add
```
