### ISSUE TITLE
Error Handling on "sync staging"

### ISSUE THREAD

**Issue by jnowland** [mdyd-dev/marketplace-kit#53]
## Expected behavior 
Error Message explaining that I must init or download the site first or at least explain why the command didn't work.

## Actual behavior
Ran into error
<details>
<summary>Error Log</summary>
```
James:hj-initial-test james$ marketplace-kit sync staging
[18:54:51] Sync mode enabled. [https://hj-initial-test.staging-sydney.near-me.com/] 
 ---
(node:11472) UnhandledPromiseRejectionWarning: Error: marketplace_builder/ does not exist.
    at watch (/usr/local/lib/node_modules/@platform-os/marketplace-kit/node_modules/node-watch/lib/watch.js:371:7)
    at ping.then (/usr/local/lib/node_modules/@platform-os/marketplace-kit/marketplace-kit-watch.js:98:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:11472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
</details>

## Steps to reproduce the problem
In a new folder set up your config file:
`marketplace-kit env add <environment> --email <your email> --url <your marketplace url>`

Once set up run:
`marketplace-kit sync staging`

### Marketplace Kit
1.1.1
### NodeJs
9.11.1
### Operating System
Mac

**Comment by jnowland** [comment]
Please note after running `marketplace-kit init` the sync command did work as expected.

**Comment by pavelloz** [comment]
For some reason its uncaught

```(node:11472) UnhandledPromiseRejectionWarning: Error: marketplace_builder/ does not exist.```


I think this is the time where we need to dive deep into error handing in promises, i remember it not being straight forward and easiest task, because it required separate book chaper.

https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch3.md
