### ISSUE TITLE
Install issue - When you do not have permission

### ISSUE THREAD

**Issue by thenexus00** [mdyd-dev/marketplace-kit#56]
## Expected behavior 
Successful install

## Actual behavior
Write access denied to /usr/local/lib/node_modules

## Steps to reproduce the problem
Mac install

## Version:
Latest

### Operating System
Mac OS

### SOLUTION:

**Update the docs so you install through - 
sudo npm i -g @platform-os/marketplace-kit
This will prompt user for password and install correctly**

**Comment by pavelloz** [comment]
Basically it depends on how nodejs was installed - i added one sentence to minimize confusion. 

Done:

https://github.com/mdyd-dev/marketplace-kit/commit/d8611b18912915101942c7b731a3df3bb37dfee5

https://github.com/mdyd-dev/nearme-documentation/commit/5acefadaf594e65d8b96a203fc52fd76eb619415
