### ISSUE TITLE
[Feature Request] Create ability to ignore files from sync and deploy commands

### ISSUE THREAD

**Issue by jnowland** [mdyd-dev/marketplace-kit#57]
## Problem 
Auto generated files get sync to live server via deploy and sync command.

This is an issue when applications like dropbox or macOS auto generate files.

Others were having issues with google drive:
> Dosen't look as though you can use Google Drive for local file management. As it creates a `desktop.ini` file in every folder which was throwing an error when deploying (not syncing though)

## Proposed Solution
Other programs which have tackled this problems such as git sublime sftp create a config file or an ignore file.

This would also prevent people accidentally syncing `node_modules` if they had their install inside of `/marketplace_builder` along with sending their source files to the server.

<details>
<summary>Example of json with ignored regex</summary>
<pre>
{
    // The tab key will cycle through the settings when first created
    // Visit http://wbond.net/sublime_packages/sftp/settings for help

    // sftp, ftp or ftps
    "type": "sftp",

    "save_before_upload": true,
    "upload_on_save": true,
    "sync_down_on_open": false,
    "sync_skip_deletes": false,
    "sync_same_age": true,
    "confirm_downloads": false,
    "confirm_sync": true,
    "confirm_overwrite_newer": false,

    "host": "example.com",
    "user": "example.com/james@example.com.au",
    "password": "",
    //"port": "22",

    "remote_path": "/",
    "ignore_regexes": [
        "\\.sublime-(project|workspace)", "sftp-config(-alt\\d?)?\\.json",
        "sftp-settings\\.json", "sftp-settings\\.json.dist", "/venv/", "\\.svn/", "\\.hg/", "\\.git/",
        "\\.bzr", "_darcs", "CVS", "\\.DS_Store", "Thumbs\\.db", "desktop\\.ini",
        ".bowerrc", ".editorconfig", ".jshintrc", "gulpfile.js", "kss-node.json", "package.json", "readme.md", "\\.sass-cache", "\\.scss", "\\.hbs",
        ".ftpconfig", "/theme/src"
    ],
    //"file_permissions": "664",
    //"dir_permissions": "775",

    //"extra_list_connections": 0,

    "connect_timeout": 30,
    //"keepalive": 120,
    //"ftp_passive_mode": true,
    //"ftp_obey_passive_host": false,
    //"ssh_key_file": "~/.ssh/id_rsa",
    //"sftp_flags": ["-F", "/path/to/ssh_config"],

    //"preserve_modification_times": false,
    //"remote_time_offset_in_hours": 0,
    //"remote_encoding": "utf-8",
    //"remote_locale": "C",
    //"allow_config_upload": false,
}
</pre>
</details>

This will then allow developers to customise how they set their directories up.

There seems to be two options here:
1. Create a `.marketplace-ignore` file.
2. Prettify the `.marketplace-kit` json and include an ignore object in there that can be edited rather easy to add custom reject specific to the developer.

It would be cleaner to extended the `.marketplace-kit` and add smart defaults on `init`.

**Comment by pavelloz** [comment]
I'll wait for anyone else express if thats needed, but either way im for option 1.

Because you dont want to commit .marketplace-kit to repository and you probably want to commit .marketplace-ignore.

**Comment by darylbarnes** [comment]
I see this issue is still open.  Can someone take a look at it because our teams would really like to use Google Drive and iCloud for local file management.

**Comment by pavelloz** [comment]
It shouldnt be a problem since April 14, when we introduced whitelist for files that are synced.
https://github.com/mdyd-dev/marketplace-kit/blob/master/lib/watch-files-extensions.js

**Comment by lemingos** [comment]
Let's close for now, looks like we're good here. cc @pavelloz
