### ISSUE TITLE
README.md broken link

### ISSUE THREAD

**Issue by SplicedWeb** [mdyd-dev/marketplace-kit#80]
## Expected behavior 
Within README.md there's a link to guide
"See this guide if you don't have Partner Portal account yet." - would expect this link to go to the guide.

## Actual behavior
https://github.com/mdyd-dev/nearme-documentation/blob/master/_PlatformOS/getting-started/setup/accessing-partner-portal.md

404 page

**Comment by pavelloz** [comment]
Thank you, fixed :)

https://documentation.platform-os.com/get-started/partner-portal/inviting-new-user-to-partner-portal
