### ISSUE TITLE
Improve UX of marketplace-kit

### ISSUE THREAD

**Issue by ignacy** [mdyd-dev/marketplace-kit#83]
## Expected behavior 

I'd like to have user experience similar to what AWS Amplify CLI provides: Nice animated boxes indicating progress, "dynamic text replacement" <- not sure how to call it - try AWS Amplify CLI to see it action. This "dry run" step is also cool: "You are attempting to do XXXXX are you sure you want to continue" (Here XXXXX can be a detailed table of things that will change and where).
Those helpful tips and comments are also useful. 

I have no idea how to do most of that stuff (except tips/errors which I'll try to tackle at some point).

## Actual behavior

Not much hand holding. Boring dots for progress indication, error handling mostly just dumps JSON errors.

**Comment by ignacy** [comment]
Some "inspiration" can be found [here]( https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-cli/src/extensions/amplify-helpers)

**Comment by lemingos** [comment]
I guess something like this already has been here https://github.com/mdyd-dev/marketplace-kit/issues/45

**Comment by pavelloz** [comment]
Nah, dry-run means: it will tell you what it would have don if it was a real run
