### ISSUE TITLE
Sync failing after created of new .yml file in user_profile_types

### ISSUE THREAD

**Issue by jnorbert** [mdyd-dev/marketplace-kit#84]
## Actual behavior
http://take.ms/eXKt1

## Steps to reproduce the problem
Run marketplace-kit sync staging
Create a new .yml file in /user_profile_types

### Operating System
MacOS X

**Comment by lemingos** [comment]
removing `custom_attributes:' line results with the same issue.

**Comment by pavelloz** [comment]
Hopefully this will be a good first step:

https://github.com/mdyd-dev/marketplace-kit/pull/88

**Comment by pavelloz** [comment]
cc @jnorbert
