### ISSUE TITLE
Allow configuration of default endpoint name

### ISSUE THREAD

**Issue by pavelloz** [mdyd-dev/marketplace-kit#9]
https://github.com/mdyd-dev/marketplace-kit/blob/05917db027d78725e7da95bb428de4322dc4144b/lib/marketplace_kit/services/args_parser.rb#L4

Basically un-hardcode it -- it should be set in `.builder` file.

```
{
  "dev": {
    "url": "url",
    "default": true
  }
```

**Comment by lemingos** [comment]
+1 partners do not have localhost.

**Comment by piotrze** [comment]
Done.
