### ISSUE TITLE
Allow logs/sync to accept url of instance

### ISSUE THREAD

**Issue by pavelloz** [mdyd-dev/marketplace-kit#99]
> marketplace-kit sync https://documentation.platform-os.com

Instead of remembering the env name from .marketplace-kit

Of course auth will throw what it has to throw if user doesnt have proper rights.

**Comment by piotrze** [comment]
@pavelloz you can set `MPKIT_URL` `MPKIT_TOKEN` `MPKIT_EMAIL` as env variables, but this is probably not user friendly
